# Generated by Django 6.0.6 on 2026-07-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
