# Generated by Django 6.0.6 on 2026-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchaseorder_stock_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
